### ISSUE TITLE
Name and Group on Excercise Sheet

### ISSUE THREAD

**Issue by bothmer** [frankluebeck/OKUSON#4]
Ich would like to have  (%Group%), (%LastName%) and (%FirstName%) and available in the PDF header.

Here in Hamburg the homework part of the sheets is graded by the same person for each group. Therefore the homework of the students has to be sorted by group before grading. Unfortunately there are always quite a number of students who forget to write their group on the sheet. So an automatic solution would greatly simplify things...

**Comment by frankluebeck** [comment]
In the new version 1.4.4 the requested (%Group%), (%LastName%) and (%FirstName%)  are supported to be used in the <PDFTemplate> configuration. But they are not used by default.

(In our university we have to avoid that Matrikelnummer and name of a student are printed together. Also, our students almost never include a printout of their exercise sheet in their homework submission. So, using this new feature would not help.)

**Comment by frankluebeck** [comment]
The requested  (%Group%), (%LastName%) and (%FirstName%) are available from version 1.4.4 for use in the <PDFTemplate> configuration. But they are not used by default.

(In our university we avoid to print ID and name together. Also our students do not include the exercise sheet when they submit homework solutions.)

**Comment by bothmer** [comment]
Thanks!
