### ISSUE TITLE
 User management is not secure

### ISSUE THREAD

**Issue by ACHinrichs** [frankluebeck/OKUSON#8]
The »hashing and salting« used by okuson is in no way secure.
In okuson, the salt is not random, but consists out of the first two symbols of the password. **It is stored in plaintext.**
Furthermore, the password is "hashed" by the use of `crypt`, which only uses the lowest 7 bits of each of the first eight characters of the key.

**Comment by frankluebeck** [comment]
First: your statement about the salts is not correct. The salts used for new hashes consist of random characters.
What do you mean by "It is stored in plaintext."? If you mean the salt, then yes, this is how salts are used, see the man page of `crypt (3)`.
It is correct that `crypt` by default uses 56 Bits of the password (the lowest 7 Bits from the first 8 characters) and hashes these as passwords are hashed in classical UNIX systems.
I do not agree that this is insecure. Cracking classical UNIX passwords is still a hard task even on modern hardware. Also, the hashed passwords in OKUSON are only visible to the system- and course administrator of an OKUSON service, that is to people who have access to all data anyway.
Nevertheless, I have just commited (a22b0c0e) a change which I had in mind for a while.  This patch provides a configuration option that accesses the extensions of `crypt` provided by new enough versions of `glibc2`, e.g. SHA-512 hashes with 8 random characters as salt which hash all bits of the password.
But this does not make the password protected data much more secure. The weakest point is that users choose bad passwords (which do not become more secure by more elaborate hashes).
